<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Activation email' => '',
    'This email has already been taken.' => '',
    'Your account has been successfully activated.' => '',
    'Your account has been successfully created. Check your email for further instructions.' => '',
    'Your activation link: {url}' => '',
    'About' => 'О нас',
    'Account Settings' => 'Налаштування аккаунта',
    'Articles' => 'Статті',
    'Attachments' => 'Вкладення',
    'Backend' => 'Панель управління',
    'Body' => 'Повідомлення',
    'Check your email for further instructions.' => 'Перевірте ваш e-mail.',
    'Confirm Password' => 'Підтвердження пароля',
    'Contact' => 'Контакти',
    'E-mail' => 'E-mail',
    'Email' => 'Email',
    'Error while oauth process.' => 'Помилка під час OAuth авторизації.',
    'Female' => 'Жіноча',
    'Home' => 'Головна',
    'If you forgot your password you can reset it <a href="{link}">here</a>' => 'Якщо ви забули свій пароль, ви можете скинути його <a href="{link}">тут</a>',
    'Incorrect username or password.' => 'Неправильні им’я користувача або пароль',
    'Language' => 'Мова',
    'Log in with' => 'Увійти за допомогою',
    'Login' => 'Вхід',
    'Logout' => 'Вихід',
    'Male' => 'Чоловіча',
    'Name' => 'Ім’я',
    'Need an account? Sign up.' => 'Потрібен аккаунт? Зареєструйтесь',
    'New password was saved.' => 'Новий пароль було збережено',
    'Page not found' => 'Сторінка не знайдена',
    'Password' => 'Пароль',
    'Password reset for {name}' => 'Скидання пароля для {name}',
    'Profile settings' => 'Налаштування профілю',
    'Remember Me' => 'Запом’ятати мене',
    'Request password reset' => 'Запит на скидання пароля',
    'Reset password' => 'Скидання пароля',
    'Settings' => 'Налаштування',
    'Sign up with' => 'Створити аккаунт за допомогою',
    'Signup' => 'Реєстрація',
    'Sorry, we are unable to reset password for email provided.' => 'Вибачте, але ми не можемо скинути пароль для цього e-mail.',
    'Subject' => 'Тема',
    'Submit' => 'Відправити',
    'Thank you for contacting us. We will respond to you as soon as possible.' => 'Дякуэмо. Ми відповімо Вам якнайшвидше.',
    'There was an error sending email.' => 'Сталася помилка при відправці email',
    'This email address has already been taken.' => 'Цей e-mail вже зайнятий',
    'This username has already been taken.' => 'Це им\'я користувача вже використовується',
    'Update' => 'Зберегти',
    'User Settings' => 'Налаштування користувача',
    'Username' => 'Им\'я користувача',
    'Username or email' => 'Им’я користувача або e-mail',
    'Verification Code' => 'Код перевірки',
    'We already have a user with email {email}' => 'Користувач с e-mail {email} вже зареэстрований',
    'Welcome to {app-name}. Email with your login information was sent to your email.' => 'Вітаємо у {app-name}. Вам був надісланий e-mail с інформациєю щодо користувача',
    'Your account has been successfully saved' => 'Ваш аккаунт було успішно збережено',
    '{app-name} | Your login information' => '{app-name} | Інформація про користувача',
    
    'request_call' => 'замовити дзвінок',
    'more' => 'Детальніше',
    'offer' => 'пропонуємо',
    'panels' => 'Панелі',
    'Sandwich_panels' => 'Сендвіч панелі',
    'for_wall' => 'для Стін',
    'width' => 'Ширина',
    'depth' => 'Товщина',
    'density' => 'Щільність',
    'outer_metal_depth' => 'Зовнішня товщина металу',
    'internal_metal_depth' => 'Внутрішня товщина металу',
    'coating' => 'Покриття',
    'colored_polymer' => 'Кольоровий полімер',
    'resist' => 'Захисне покриття',
    'film' => 'Плівка',
    'for_roof' => 'для даху',
    'advantages' => 'Переваги',
    'sandiwich-panels' => 'сендвіч-панелей',
    'calculation' => 'ОТРИМАЙТЕ індивідуальний прорахунок ВАРТОСТІ',
    'projects' => 'Проекти з сендвіч-панелей',
    'equipments' => 'Холодильне обладнання',
    'contacts' => 'КОНТАКТИ',
    'address' => 'м.Рівне вул. Старицького 45',
    'questions' => 'ЗАЛИШИЛИСЯ ЗАПИТАННЯ?',
    'request_call_managers' => "Замовте зворотній дзвінок і наші менеджери зв'яжуться з Вами найближчим часом",
    'thanks' => 'Дякуємо за звернення',
    'managers' => "Наші менеджери зв'яжуться з Вами найближчим часом",
    'Request_call' => 'Замовити дзвінок',
    'placeholder_name' => "Введіть Ваше ім`я",
    'placeholder_email' => 'Введіть Ваш email',
    'placeholder_phone' => 'Введіть Ваш телефон',
    
];
