<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Activation email' => '',
    'This email has already been taken.' => '',
    'Your account has been successfully activated.' => '',
    'Your account has been successfully created. Check your email for further instructions.' => '',
    'Your activation link: {url}' => '',
    'About' => 'О нас',
    'Account Settings' => 'Настройки аккаунта',
    'Articles' => 'Статьи',
    'Attachments' => 'Приложения',
    'Backend' => 'Панель управления',
    'Body' => 'Сообщение',
    'Check your email for further instructions.' => 'Проверьте ваш e-mail.',
    'Confirm Password' => 'Подтвердите пароль',
    'Contact' => 'Контакты',
    'E-mail' => 'E-mail',
    'Email' => 'Email',
    'Error while oauth process.' => 'Ошибка в процессе OAuth авторизации.',
    'Female' => 'Женский',
    'Home' => 'Главная',
    'If you forgot your password you can reset it <a href="{link}">here</a>' => 'Если вы забыли пароль, вы можете сбросить его <a href="{link}">здесь</a>',
    'Incorrect username or password.' => 'Неправильный логин или пароль.',
    'Language' => 'Язык',
    'Log in with' => 'Войти с помощью',
    'Login' => 'Вход',
    'Logout' => 'Выход',
    'Male' => 'Мужской',
    'Name' => 'Имя',
    'Need an account? Sign up.' => 'Нужен аккаунт? Зарегистрируйтесь',
    'New password was saved.' => 'Новый пароль был сохранен',
    'Page not found' => 'Страница не найдена',
    'Password' => 'Пароль',
    'Password reset for {name}' => 'Сброс пароля для {name}',
    'Profile settings' => 'Настройки профиля',
    'Remember Me' => 'Запомнить меня',
    'Request password reset' => 'Запрос сброса пароля',
    'Reset password' => 'Сброс пароля',
    'Settings' => 'Настройки',
    'Sign up with' => 'Создать аккаунт с помощью',
    'Signup' => 'Регистрация',
    'Sorry, we are unable to reset password for email provided.' => 'Извините, мы не можем сбросить пароль для этого e-mail.',
    'Subject' => 'Тема',
    'Submit' => 'Отправить',
    'Thank you for contacting us. We will respond to you as soon as possible.' => 'Спасибо. Мы свяжемся с Вами в ближайщее время',
    'There was an error sending email.' => 'Ошибка при отправке сообщения.',
    'This email address has already been taken.' => 'Этот e-mail уже занят',
    'This username has already been taken.' => 'Это имя пользователя уже занято',
    'Update' => 'Редактировать',
    'User Settings' => 'Настройки пользователя',
    'Username' => 'Имя пользователя',
    'Username or email' => 'Имя пользователя или e-mail',
    'Verification Code' => 'Проверочный код',
    'We already have a user with email {email}' => 'Пользователь с email {email} уже зарегистрирован.',
    'Welcome to {app-name}. Email with your login information was sent to your email.' => 'Добро пожаловать в {app-name}. E-mail с информацией о пользователе был отправлен на вашу почту.',
    'Your account has been successfully saved' => 'Ваш аккаунт был успешно сохранен',
    '{app-name} | Your login information' => '{app-name} | Информация о пользователе',
    
    'get a call' => 'заказать звонок',
    'More' => 'Подробнее',
    'offer' => 'предлагаем',
    'Panels' => 'Панели',
    'Sandwich panels' => 'Сэндвич панели',
    'for wall' => 'для Стен',
    'Width' => 'Ширина',
    'Depth' => 'Толщина',
    'Density' => 'Плотность',
    'Outer metal depth' => 'Внешняя сторона металла',
    'Internal metal depth' => 'Внутренняя сторона металла',
    'Coating' => 'покрытие',
    'Colored_polymer' => 'Цветной полимер',
    'Resist' => 'Защитное покрытие',
    'Film' => 'Пленка',
    'for roof' => 'для крыши',
    'Advantages' => 'Преимущества',
    'sandiwich-panels' => 'сэндвич-панелей',
    'GET VALUE individual miscalculation' => 'ПОЛУЧИТЕ индивидуальный расчет СТОИМОСТИ',
    'Projects of sandwich panels' => 'Проекты из сэндвич-панелей',
    'Refrigeration equipment' => 'Холодильное оборудование',
    'CONTACTS' => 'КОНТАКТЫ',
    'Rivne Str. Staritskogo 45' => 'г.Ровно ул. Старицкого 45',
    'STILL HAVE QUESTIONS?' => 'ОСТАЛИСЬ ВОПРОСЫ?',
    'Sign up for a call back and our managers will contact you shortly' => "Закажите обратный звонок и наши менеджеры свяжутся с Вами в ближайшее время",
    'Thank you for writing' => 'Спасибо за обращение',
    'Our managers will contact you shortly' => "Наши менеджеры свяжутся с Вами в ближайшее время",
    'Get a call' => 'Заказать звонок',
    'Enter your name' => "Введите Ваше имя",
    'Enter your email' => 'Введите Ваш email',
    'Enter your phone' => 'Введите Ваш телефон',
    
    
];
